# Generated by Django 5.2.17 on 2026-10-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0004_rockcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rock',
            name='is_company_rock',
            field=models.BooleanField(default=False, help_text="Company-wide Rocks appear on the VTO. Other Rocks stay on their team's own list."),
        ),
    ]
