# Generated by Django 5.2.17 on 2026-10-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_company_issue',
            field=models.BooleanField(default=False, help_text="Company-wide long-term Issues appear on the VTO. Other Issues stay on their team's own list."),
        ),
    ]
